### ISSUE TITLE
Stuck on tutorial

### ISSUE THREAD

**Issue by noon3** [Bradymck/Game-Of-Memes#1]
During the tutorial session, I couldn't continue it after I reached "Every turn you will draw a card from your deck" step. It says that 'click to continue' but it doesn't react to my left clicks.

**To Reproduce**
1. Game type: Tutorial
2. Card or feature affected: _(click to continue)_ button
3. Other details: 

**Expected behavior**
I just want to continue the tutorial. lol.

**Screenshots**
![bug_1](https://user-images.githubusercontent.com/10882177/60267452-37c4e100-9925-11e9-9ca1-b02c33dbcb6b.png)

**Browser**
Firefox Quantum 67.0.4 (64-bit)/ Privacy mode

**Additional context**
none

**Comment by Bradymck** [comment]
This issue should be resolved now.
