### ISSUE TITLE
Can't start AI match-up

### ISSUE THREAD

**Issue by noon3** [Bradymck/Game-Of-Memes#2]
**Describe the bug**
I tried to find AI opponents but seems like they are too scared of me 😨 

**To Reproduce**
Steps to reproduce the behavior: Just start AI match
1. Game type: Start AI/Boss Battle
2. Card or feature affected: **It just keep loading the page...**
3. Other details: .

**Expected behavior**
Need more stronk AI at least who can stand up to me 💪 
**Screenshots**
![bug_2](https://user-images.githubusercontent.com/10882177/60268308-17962180-9927-11e9-93fb-3df4fb08df57.png)

**Browser**
Firefox Quantum 67.0.4 (64-bit)/ Privacy mode

**Additional context**
none

**Comment by Bradymck** [comment]
This seems to be a privacy mode issue. I get the same thing. It's also something I may not be able to fix since it's on the platform's end. Closing this out for now but I will test and see if I find a workaround.
